org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

minecraft_version=1.21.5
minecraft_version_range=[1.21.5,1.21.6)
enabled_platforms=fabric,neoforge

archives_base_name=anvilclient
mod_version=2.0.0
maven_group=anvilclient

architectury_version=16.1.4

fabric_loader_version=0.17.2
fabric_api_version=0.128.2+1.21.5

parchment_minecraft_version=1.21.5
parchment_version=2025.06.15

neo_version=21.5.93
neo_version_range=[21.5,)
loader_version_range=[2,)

modmenu_version=14.0.0-rc.2
