org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.21.9)
enabled_platforms=fabric,neoforge

archives_base_name=anvilclient
mod_version=2.0.0
maven_group=anvilclient

architectury_version=17.0.8

fabric_loader_version=0.17.2
fabric_api_version=0.133.0+1.21.8

parchment_minecraft_version=1.21.8
parchment_version=2025.07.20

neo_version=21.8.46
neo_version_range=[21.8,)
loader_version_range=[2,)

modmenu_version=15.0.0
