modLoader = "javafml"
loaderVersion = "${loader_version_range}"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId="anvilclient"
version="${mod_version}"
displayName="Anvilclient"
displayURL="https://anvil-mods.github.io"
displayTest="IGNORE_ALL_VERSION"
logoFile="assets/anvilclient/anvilclient.png"
credits=""
authors="Amboss_Mann"
description='''
A utility mod for Minecraft
'''

[[mixins]]
config = "anvilclient.mixins.json"

[[dependencies.anvilclient]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.anvilclient]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.anvilclient]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version})"
ordering = "AFTER"
side = "CLIENT"